[detext] Adding multilabel classification
linkedin/detext pull request #76
Opened 2022-08-24 04:37 UTC by amberkaur1

# Description

Added multi-label classification task to detext. Updated input label format to array (shape [num_classes], assuming one-hot array input), changed loss and activation functions, added precision/recall metrics. Passed unit tests on detect-dev mp while being backwards compatible. 

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## List all changes 
Please list all changes in the commit.
* Added MULTILABEL_CLASSIFICATION TaskType and fixed
* Updated input label format to array (shape [num_classes], assuming one-hot array input
* Changed loss and activation functions for multi-label classification
* Added precision/recall metrics

# Testing
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Passed unit tests on detect-dev mp while being backwards compatible. Also passed unit tests on li-detext, but full pipeline with real data yet to be confirmed

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-05 21:06 UTC, wang-jia-rui requested changes
Thank you for your effort on multilabel classification! Please check my comments below.

2022-10-05 21:06 UTC, wang-jia-rui commented on src/detext/train/metrics.py
> +        probabilities = tf.round(tf.nn.sigmoid(scores))  # Convert to probabilities in range [0, 1]
After rounding the probabilities will become predictions, please change the variable name.

2022-10-05 21:06 UTC, wang-jia-rui commented on src/detext/train/metrics.py
> +        return super(PrecisionMetric, self).update_state(labels, probabilities, sample_weight)
Please also update the variable name here.

2022-10-05 21:06 UTC, wang-jia-rui commented on src/detext/train/metrics.py
> +        probabilities = tf.round(tf.nn.sigmoid(scores))  # Convert to probabilities in range [0, 1]
Please also update the variable name in RecallMetric

2022-10-07 22:35 UTC, amberkaur1 commented
> Thank you for your effort on multilabel classification! Please check my comments below.

2023-03-02 22:03 UTC, merged